# .readthedocs.yaml
# Read the Docs configuration file for i18n documentation
# See https://docs.readthedocs.com/en/stable/config-file/v2.html for details
#
# IMPORTANT: For multi-language support with i18n:
# 1. Create two separate projects in ReadTheDocs admin panel:
#    - Main project (English): vibemq (Language: English)
#    - Translation project (Russian): vibemq-ru (Language: Russian)
# 2. In the main project admin, go to Translations and add Russian project
# 3. Each project uses the same .readthedocs.yaml and docs/conf.py
# 4. Read the Docs automatically sets READTHEDOCS_LANGUAGE environment variable
#    (values: 'en' for English, 'ru' for Russian)
# 5. The conf.py reads this variable to set the correct language

version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - gettext
  jobs:
    post_checkout:
      # Cancel building pull requests when there aren't changes in the docs directory or YAML file.
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && ! git diff --quiet origin/main -- docs/ .readthedocs.yaml; then
          exit 1;
        fi

# Build documentation with i18n support
# The language is determined by READTHEDOCS_LANGUAGE environment variable
# which is automatically set by Read the Docs based on project language settings
# Values: 'en' for English project, 'ru' for Russian project
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Declare the Python requirements required to build your documentation
python:
  install:
    - requirements: docs/requirements.txt

# Submodules configuration (if needed)
submodules:
  include: []
  recursive: false
